index.html, news.html, poi.html
- Fixed Logo-Link to index.html
- Removed currently unneccessary alert box
- Removed Link to Categories (most users will not be able to edit these)
- Added Box for Intro
- Added Sample Page for POI
=> Small Changes

app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/controllers/news_items_controller.rb, app/controllers/point_of_interests_controller.rb, app/controllers/tours_controller.rb, app/views/news_items/form_partials/_categories_form.html.erb
Load categories from server and display them as a dropdown list in news form
=> Categorylist from Server

app/controllers/data_provider_controller.rb, app/controllers/events_controller.rb, app/controllers/news_items_controller.rb, app/controllers/point_of_interests_controller.rb, app/controllers/tours_controller.rb, app/javascript/packs/application.js, app/views/events/_form.html.erb, app/views/events/form_partials/_event_contacts.html.erb, app/views/layouts/_sidebar_navigation.html.erb, app/views/news_items/_form.html.erb, app/views/point_of_interests/_form.html.erb, app/views/point_of_interests/edit.html.erb, app/views/point_of_interests/index.html.erb, app/views/point_of_interests/new.html.erb, app/views/shared/partials/_categories_form.html.erb, app/views/shared/partials/_operating_company_form.html.erb, app/views/shared/partials/_organizer_form.html.erb, app/views/shared/partials/_price_informations_form.html.erb, app/views/shared/partials/_web_url_form.html.erb
- add active style for sidebar navigation entries
- added logics in controller
- added views
- refactored price informations which were used at events only before, to use it for points of interest as well now
- needed to adjust js for nested has_many functionality
- formatted all <<~GRAPHQL heredocs because syntax highlightings were broken
- params with #{...} needs to be on a single line
- adjusted margins and `<hr />`s
- handle validation for operation_company :name
#16
---
=> feat: implement editable points of interest

app/views/point_of_interests/_form.html.erb
- added check for presence of new `role_lunch` in case of rendering the lunch form
=> chore: use role lunch

app/controllers/news_items_controller.rb, app/views/news_items/_form.html.erb, app/views/news_items/index.html.erb
=> feat(push): deactivate editing after push notifications sent

app/controllers/point_of_interests_controller.rb, app/controllers/tours_controller.rb, app/views/tours/_form.html.erb, app/views/tours/edit.html.erb, app/views/tours/index.html.erb, app/views/tours/new.html.erb
- added attributes to query for to be able to setup the form
- added form and hints partial with all needed fields
- updated tours controller to process all form data
in the way the main server needs them
- special processing of length_km as it needs
to be an integer
=> Touren bearbeitbar machen im CMS

app/javascript/packs/application.js, app/views/layouts/application.html.erb, package.json, yarn.lock
Datumsspalten in Tabelle werden mit Hilfe des moment.js plugins aufsteigend/absteigend sortiert.
=> CMS Sortierung nach Datum

app/views/jobs/_form.html.erb
- added validation to employment_type field
- added placeholder to employment_type field
- changed sequence of form fields
SVA-201
=> CMS Jobs Optimierungen

app/assets/stylesheets/custom.css, app/views/jobs/form_partials/_job_content.html.erb, app/views/point_of_interests/form_partials/_lunches_form.html.erb, app/views/shared/partials/_content_blocks_form.html.erb
- added a class to identify the "Text" textareas
- added a min height style for these textareas identified by the ckeditor next to the given class
SVA-206
---
=> feat(textarea size): set min height

app/controllers/surveys_controller.rb, app/helpers/i18n_helper.rb, app/views/layouts/_sidebar_navigation.html.erb, app/views/surveys/index.html.erb, config/routes.rb
- setup survey routes
- added survey area entrance in sidebar
- TODO: correct icon is missing
- added index view based on existing index views adjusted for surveys
- added survey controller with index method to request necessary data
- created a helper method to format i18n jsons in a multiline way with html <br /> to be presented in a readable way in the table
SVA2-7
TODO done, icon edited:
=> feat(surveys): add index page with table

app/controllers/surveys_controller.rb
- added destroy method called from index table
SVA2-6
(_deleted id 7_)
=> feat(surveys): delete from index

app/controllers/surveys_controller.rb, app/views/shared/partials/_dates_form.html.erb, app/views/surveys/_form.html.erb, app/views/surveys/form_partials/_response_options_form.html.erb, app/views/surveys/new.html.erb
- added controller actions to be able to create surveys based on existing controllers for other resources
- added form and form fields to create everything that is necessary for a survey
SVA2-3
=> feat(surveys): create surveys

app/controllers/surveys_controller.rb, app/services/converter/base.rb, app/views/surveys/_form.html.erb, app/views/surveys/edit.html.erb, app/views/surveys/form_partials/_response_options_form.html.erb
979789c feat(survey): show survey details in a edit form
e60b4ef feat(update survey): add action and logics to update surveys
f7e1907 chore(survey): remove default end date
d012ac8 feat(update survey): add hint text for editing response options
SVA2-4 SVA2-5
=> feat(update survey)

app/views/surveys/form_partials/_response_options_form.html.erb
=> feat(survey): show votes per response option

app/assets/stylesheets/custom.css, app/views/dashboard/index.html.erb, app/views/events/index.html.erb, app/views/news_items/_form.html.erb, app/views/news_items/index.html.erb, app/views/point_of_interests/_form.html.erb, app/views/point_of_interests/form_partials/_lunch_offers_form.html.erb, app/views/point_of_interests/form_partials/_lunches_form.html.erb, app/views/point_of_interests/index.html.erb, app/views/shared/partials/_categories_form.html.erb, app/views/shared/partials/_contacts_form.html.erb, app/views/shared/partials/_content_blocks_form.html.erb, app/views/shared/partials/_media_contents_form.html.erb, app/views/shared/partials/_opening_hours_form.html.erb, app/views/shared/partials/_price_informations_form.html.erb, app/views/shared/partials/_url_form.html.erb, app/views/shared/partials/_web_url_form.html.erb, app/views/tours/_form.html.erb, app/views/tours/index.html.erb, app/views/waste_calendar/index.html.erb
- instead of remove wording just displaying a trash can
- changed wording of "adding" and also used icon here
SVA-228
=> CMS Bereiche überarbeiten

app/services/converter/base.rb, app/views/shared/partials/_dates_form.html.erb
Nice 🐞 s, but better to avoid them.
=> Fix errors on data handling

app/controllers/events_controller.rb, app/controllers/point_of_interests_controller.rb, app/helpers/form_helper.rb, app/javascript/partials/_nested_content_block_form.js, app/javascript/partials/_nested_forms.js, app/javascript/partials/_nested_lunch_form.js, app/views/jobs/_form.html.erb, app/views/jobs/form_partials/_job_content.html.erb, app/views/offers/_form.html.erb, app/views/point_of_interests/form_partials/_lunch_offers_form.html.erb, app/views/point_of_interests/form_partials/_lunches_form.html.erb, app/views/shared/partials/_contact_form.html.erb, app/views/shared/partials/_contacts_form.html.erb, app/views/shared/partials/_content_blocks_form.html.erb, app/views/shared/partials/_dates_form.html.erb, app/views/shared/partials/_media_contents_form.html.erb, app/views/shared/partials/_opening_hours_form.html.erb, app/views/shared/partials/_price_informations_form.html.erb, app/views/shared/partials/_url_form.html.erb, app/views/shared/partials/_web_url_form.html.erb
- added form helper that checks objets for presence of field values
- therefore every form partials needs to define the fields that should be rendered and checked
- hide sections initially if empty using that new helper
- added js logic in nested form logics to make hidden sections visible
- dates form got a special `force_visibility` property now that is needed in launch form to render empty date fields
- linted ruby `'`s to `"`s
SVA-248
=> Hide initial sections in forms

app/controllers/data_provider_controller.rb, app/controllers/survey_comments_controller.rb, app/controllers/surveys_controller.rb, app/helpers/application_helper.rb, app/views/layouts/_sidebar_navigation.html.erb, app/views/survey_comments/_modal_message.html.erb, app/views/survey_comments/index.html.erb, app/views/surveys/index.html.erb, config/routes.rb
4ad5e41 feat(survey comments): add comments overview
41c46eb feat(survey comments): add visibility switch
7331e67 feat(survey comments): add modal for long message texts
---
|survey index|survey comments index with open long message modal|
|---|---|
|![Bildschirmfoto 2021-07-07 um 12 51 27](https://user-images.githubusercontent.com/1942953/124747349-1cccd480-df22-11eb-998e-29c312a6567d.png)|![Bildschirmfoto 2021-07-07 um 12 42 01](https://user-images.githubusercontent.com/1942953/124747365-20605b80-df22-11eb-9763-01fbfccc0d87.png)|
|very long message are scrollable|in the modal|
|---|---|
|![Bildschirmfoto 2021-07-07 um 12 43 50](https://user-images.githubusercontent.com/1942953/124747447-3837df80-df22-11eb-8460-fa0c18063e5d.png)|![Bildschirmfoto 2021-07-07 um 12 43 …
=> Comments for surveys

app/views/constructions/index.html.erb, app/views/events/index.html.erb, app/views/jobs/index.html.erb, app/views/news_items/index.html.erb, app/views/offers/index.html.erb, app/views/point_of_interests/index.html.erb, app/views/tours/index.html.erb
=> refactor: update access of data provider name on index pages

app/controllers/constructions_controller.rb, app/controllers/jobs_controller.rb, app/controllers/offers_controller.rb, app/controllers/surveys_controller.rb, app/views/constructions/index.html.erb, app/views/jobs/index.html.erb, app/views/offers/index.html.erb, app/views/surveys/index.html.erb
added dates to constructions, surveys, jobs and offers index tables.
SVA-212
=> feat: add dates to index views

app/assets/stylesheets/custom.css, app/views/constructions/index.html.erb, app/views/events/index.html.erb, app/views/jobs/index.html.erb, app/views/news_items/index.html.erb, app/views/offers/index.html.erb, app/views/point_of_interests/index.html.erb, app/views/surveys/index.html.erb, app/views/tours/index.html.erb, app/views/waste_calendar/index.html.erb
- when row to small, the button should wrap
- so the button doesn't have left margin when displayed in next row, give headline margin
- added row-gap class, to have space between headline and button on mobile
- when screen is small, the date cells shouldn't wrap
=> CMS Button + Date cell Changes

app/controllers/constructions_controller.rb, app/controllers/events_controller.rb, app/controllers/news_items_controller.rb, app/controllers/point_of_interests_controller.rb, app/controllers/tours_controller.rb, app/helpers/form_helper.rb, app/javascript/partials/_nested_content_block_form.js, app/javascript/partials/_nested_forms.js, app/javascript/partials/_nested_lunch_form.js, app/views/point_of_interests/_form.html.erb, app/views/point_of_interests/form_partials/_attributes_form.html.erb, app/views/point_of_interests/form_partials/_lunches_form.html.erb, app/views/shared/partials/_categories_form.html.erb, app/views/shared/partials/_media_contents_form.html.erb
78f208c feat: hide media contents initially
3d77961 feat(categories form): implement logic to hide initial section
bd24de3 fix: added :create to before_action list for loading categories
252cb0f fix: required name for points of interest
eeea822 feat(lunches form): implement logic to hide initial section
3b5c95e fix: lunch text was never saved
8e827a9 refactor(form js): named callback params correctly
SVA-248
=> Better initial forms

app/views/surveys/index.html.erb
display question instead of survey title
SVA2-28
=> feat(survey): show question instead of title

app/controllers/surveys_controller.rb, app/views/surveys/_form.html.erb, app/views/surveys/index.html.erb
SVA-363
|edit|index|
|---|---|
|![Bildschirmfoto 2021-11-26 um 17 08 11](https://user-images.githubusercontent.com/1942953/143607772-5d704118-611c-4f0b-8589-77ab5ffd0801.png)|![Bildschirmfoto 2021-11-26 um 17 09 58](https://user-images.githubusercontent.com/1942953/143607784-73beb306-698c-45a1-8a5f-f34e5cf7b2b8.png)|
=> feat(surveys): use and edit `can_comment`

app/controllers/surveys_controller.rb, app/views/surveys/_form.html.erb
=> feat(surveys): use and edit `question_allow_multiple_responses`

app/controllers/surveys_controller.rb, app/views/surveys/_form.html.erb, app/views/surveys/form_partials/_response_options_form.html.erb
=> feat(surveys): use and edit `is_multilingual`

app/javascript/packs/application.js
- adjusted usage of moment for dataTables
and added additional type of date format
which resulted in working sortable columns
with different formats
SVA-373
=> fix: date columns sorting

app/controllers/constructions_controller.rb
=> fix(construction): allows save for name only

Gemfile, Gemfile.lock, app/assets/stylesheets/custom.css, app/controllers/minio_controller.rb, app/controllers/session_controller.rb, app/javascript/packs/application.js, app/javascript/packs/fileupload.js, app/javascript/partials/_nested_forms.js, app/models/user.rb, app/views/shared/partials/_fileupload.html.erb, app/views/shared/partials/_media_contents_form.html.erb, config/routes.rb, package.json, yarn.lock
[SVA-226](https://tpwd.atlassian.net/browse/SVA-226)
[PR in Mainserver](https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/305)
Screenshots:
**Normal state:**
**Uploading state:**
**Upload done with img preview and url copied to input:**
**TODO**:
=> Feature: CMS File upload

app/assets/stylesheets/custom.css, app/controllers/tours_controller.rb, app/javascript/partials/_fileupload.js, app/javascript/partials/_nested_content_block_form.js, app/javascript/partials/_nested_forms.js, app/javascript/partials/_nested_lunch_form.js, app/views/shared/partials/_fileupload.html.erb, app/views/shared/partials/_image_upload.html.erb, app/views/shared/partials/_media_contents_form.html.erb, app/views/tours/_form.html.erb, app/views/tours/form_partials/_ar_file_upload.html.erb, app/views/tours/form_partials/_tour_path.html.erb, app/views/tours/form_partials/_tour_stop_ar_form.html.erb, app/views/tours/form_partials/_tour_stop_form.html.erb
This implements forms for tour stops with a partial for AR data including file uploads.
**TODOs**:
SVA-572
=> feat(tour): add form for tour stops

app/services/converter/base.rb
- in https://github.com/github/graphql-client/blob/v0.15.0/lib/graphql/client.rb#L123-L167 there occur some errors when parsing strings with a certain regex, so we need to append a space after "..." in the matched string
=> fix(mutation): safe parse built mutation string

app/controllers/application_controller.rb, app/controllers/constructions_controller.rb, app/controllers/encounters_supports_controller.rb, app/controllers/events_controller.rb, app/controllers/jobs_controller.rb, app/controllers/news_items_controller.rb, app/controllers/offers_controller.rb, app/controllers/point_of_interests_controller.rb, app/controllers/static_contents_controller.rb, app/controllers/survey_comments_controller.rb, app/controllers/surveys_controller.rb, app/controllers/tours_controller.rb, app/controllers/waste_calendar_controller.rb
- added check of user roles before actions and redirect to root if not allowed
=> feat: redirections if not in role

app/controllers/push_notifications_controller.rb, app/views/dashboard/index.html.erb, app/views/layouts/_sidebar_navigation.html.erb, app/views/push_notifications/new.html.erb, config/routes.rb
https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/358 is required to make the request for sending work
SVA-710
|navigation|dashboard|form|sent|
|---|---|---|---|
|![SCR-20221110-qjh](https://user-images.githubusercontent.com/1942953/201173064-27f702d0-d062-4202-a47b-40a98bd298e6.png)|![Bildschirmfoto am 2022-11-10 um 19 06 19](https://user-images.githubusercontent.com/1942953/201173086-812e263e-5751-45b8-882b-b01f6138a711.png)|![Bildschirmfoto am 2022-11-10 um 19 06 43](https://user-images.githubusercontent.com/1942953/201173112-01fd2c1e-3f0c-49b3-bd05-bfe802e0961d.png)|![Bildschirmfoto am 2022-11-10 um 19 06 10](https://user-images.githubusercontent.com/1942953/201173132-96a7060c-3ed0-46fe-b61c-eda18b865a11.png)|
=> feat(push notifications): create with title and body for all devices

app/controllers/push_notifications_controller.rb, app/views/push_notifications/new.html.erb
https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/359 is required
SVA-710
|new field|select values|
|---|---|
|<img width="512" alt="SCR-20221111-ij0" src="https://user-images.githubusercontent.com/1942953/201339625-a8b5709c-1a6b-4dcc-96c7-fbaf6ab8dcbe.png">|<img width="550" alt="SCR-20221111-ij3" src="https://user-images.githubusercontent.com/1942953/201339639-a466960d-336b-4158-ae52-6453e7ece3e5.png">|
=> feat(push notifications): add data provider id selection

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/deadlines_controller.rb, app/controllers/waste_calendar_controller.rb, app/views/constructions/_form.html.erb, app/views/constructions/index.html.erb, app/views/dashboard/index.html.erb, app/views/deadlines/_form.html.erb, app/views/deadlines/create.html.erb, app/views/deadlines/destroy.html.erb, app/views/deadlines/edit.html.erb, app/views/deadlines/index.html.erb, app/views/deadlines/new.html.erb, app/views/deadlines/show.html.erb, app/views/deadlines/update.html.erb, app/views/jobs/_form.html.erb, app/views/layouts/_sidebar_navigation.html.erb, app/views/offers/_form.html.erb, app/views/shared/partials/_categories_form.html.erb, app/views/shared/partials/_dates_form.html.erb, app/views/shared/partials/_fileupload.html.erb, config/routes.rb
These are the first steps to implement the whole "deadlines" feature to manage fix dates with several push notification possibilities.
SVA-710
|index|new/edit|
|---|---|
|<img width="1503" alt="image" src="https://user-images.githubusercontent.com/1942953/201393987-f62a97e8-050e-4a50-a3d5-7a0cf02e9d36.png">|![SCR-20221111-okt](https://user-images.githubusercontent.com/1942953/201394004-4254294d-0d59-4d35-b81f-bdf90e7f8a84.png)|
=> feat(deadlines): add routes, in navigation and on dashboard, controller and views

app/controllers/dashboard_controller.rb, app/controllers/data_provider_controller.rb, app/controllers/noticeboards_controller.rb, app/views/dashboard/index.html.erb, app/views/layouts/_sidebar_navigation.html.erb, app/views/noticeboards/_modal_content.html.erb, app/views/noticeboards/index.html.erb, config/routes.rb
- created all resources that are needed for the index screen to display the important data and functions
SVA-739
|index|content modal|
|---|---|
|![SCR-20221129-h6c](https://user-images.githubusercontent.com/1942953/204516915-7a243abb-0001-4846-b9f3-33925ff605a8.png)|![SCR-20221129-h6i](https://user-images.githubusercontent.com/1942953/204516990-55596843-1421-46e3-b4cd-65ad9ac71a00.png)|
=> feat(noticeboard): implement index screen

app/controllers/deadlines_controller.rb, app/javascript/partials/_nested_forms.js, app/views/deadlines/_form.html.erb, app/views/shared/partials/_push_notifications_form.html.erb
=> feat(deadlines): complete form with push notifications

app/controllers/dashboard_controller.rb, app/controllers/defect_reports_controller.rb, app/javascript/partials/_leaflet_map.js, app/views/dashboard/index.html.erb, app/views/defect_reports/_modal_content.html.erb, app/views/defect_reports/index.html.erb, app/views/layouts/_sidebar_navigation.html.erb, config/routes.rb
- added defect report routes, dashboard element, navigation entry
- added leaflet map logics to make them work in modals, that are hidden on initial load
SVA-738
=> feat(defect report): implement index with modal

app/controllers/events_controller.rb, app/services/converter/base.rb, app/views/events/_form.html.erb, app/views/events/edit.html.erb, config/application.rb, config/locales/de.yml, config/locales/en.yml
This Pull Request introduces two significant enhancements to our event management system.
1. Add "Copy Event" button to Event Edit page with changes:
We have added a new "Copy Event" (Kopieren) button on the Event Edit page. This button allows users to quickly create a duplicate of an existing event, retaining all the event details from the original, including any changes made during the edit session. This feature helps in efficient event management, especially when similar events occur frequently, by reducing the effort and time required to input the same details repeatedly.
**Screenshot showing the 'Copy' button located below the 'Save' button**
2. Set copied event visibility to 'false' by default:
We have further enhanced the event copying function by setting the copied event's …
=> feat: enhance event management functionality
