app/controllers/news_items_controller.rb
app/javascript/packs/application.js
app/views/news_items/form_partials/_content_blocks_form.html.erb
app/views/shared/partials/_media_contents_form.html.erb

- we need more logic after adding a block of contents
to make the inner logic work
- the https://github.com/kanety/jquery-nested-form is providing
events, which we can use
- added a new class for nested media if rendered within
content block
- otherwise default still "nested-media"
- started working on new js logic for the new class to be able
to make deeply nested forms work

Add additional logic for deeply nested forms

---

app/controllers/point_of_interests_controller.rb
app/javascript/partials/_nested_forms.js
app/views/point_of_interests/_form.html.erb
app/views/shared/partials/_opening_hours_form.html.erb

feat(edit point of interest): avoid empty objects to be transmitted
- added deeper checks for presence of the following data:
- addresses
- contact
- mediaContents
- price_informations
- lunches
- adjusted two form renderings to render empty fields if there are no initial data
- if the server does not get certain attributes, there will be none of them created without further empty attributes
feat(edit point of interest): add opening hours form
SVA-183
Fixes #42
Fixes #43
Fixes #44

Avoid empty objects and add opening hours form

---

app/assets/stylesheets/custom.css
app/javascript/packs/application.js
app/views/layouts/application.html.erb

- this places the sidebar over the page content
- it always renders initially in toggled mode now to not cover page contents
- the page itself needs to move the width of the toggled sidebar to the left, so that contents are not covered
- therefore on mobile the top toggler needs to move as well if the sidebar is opened
SVA-206
---
please play around to see if it feels ok in several places

feat(sidebar): position over content

---

app/views/surveys/index.html.erb

- updated text in "data-confirm"
- linted `link_to` params in multiple lines for better readability
SVA2-6

feat(surveys): update confirmation text for alert on deletion

---

app/views/constructions/_form.html.erb
app/views/jobs/_form.html.erb
app/views/offers/_form.html.erb
app/views/surveys/_form.html.erb

- added `force_visibility: true` to the date fields which are empty because we want to show them always and there are no "add date" buttons to make them visible

fix(date fields): force visibility for all date fields

---

app/controllers/constructions_controller.rb
app/views/constructions/_form.html.erb
app/views/shared/partials/_restrictions_form.html.erb

- used a default text area for content block body instead of html
- added a location name to enter beside geo coordinates
- refactored form view to reduce a list of locations iteration
- refactored usages of global `@construction` in views to certain local variables
SVA-212
---

feat(constructions): update form fields

---

app/views/point_of_interests/form_partials/_lunches_form.html.erb

SVA-265
to avoid
which will not be rendered as html in the mobile app

fix(lunch text): remove html ability of textarea

---

app/javascript/packs/application.js

On mobile scroll the navbar dissappears, because the resize event gets triggered
- jquery event gets triggered on mobile scroll, as the address bar gets smaller in height
- therefore check for width difference at the resize event and only toggle when there is a width difference
SVA-261

Prevent resize event from triggering

---

app/controllers/news_items_controller.rb
app/views/news_items/_form.html.erb
app/views/news_items/index.html.erb
app/views/shared/partials/_categories_form.html.erb

- added check for nested values when converting params to avoid creation of empty ones
- made at least one category input visible on load for news items
- added flashs and redirect + return for create and edit actions if no category selected
SVA-281

feat: make a category required for new items

---

app/views/surveys/_form.html.erb
app/views/surveys/form_partials/_response_options_form.html.erb

- to be able to use html contents reasonable
SVA-364
|before|after|
|---|---|
|![Bildschirmfoto 2021-11-26 um 16 34 58](https://user-images.githubusercontent.com/1942953/143604180-b6e39297-ff07-454f-b837-636b29434568.png)|![Bildschirmfoto 2021-11-26 um 16 36 49](https://user-images.githubusercontent.com/1942953/143604192-32b28a30-2b67-434c-9760-7b063777d040.png)|

feat(surveys): use text area for response options

---

app/controllers/point_of_interests_controller.rb
app/views/shared/partials/_opening_hours_form.html.erb

- added hidden field for `:open` check box, as rails
does not render it automatically with the `.check_box`
when passed `false` as last param (unchecked value)
- cast `"false"` to boolean in parameters being sent to the
server, as this does not happen automatically and produces
errors
- somehow magic happens for check_box value "true" and it
is not needed
- updated default check box value to respect to objects value
if given
SVA-434
---

fix(opening hours): save unchecked check box

---

app/controllers/constructions_controller.rb
app/controllers/events_controller.rb
app/controllers/jobs_controller.rb
app/controllers/news_items_controller.rb
app/controllers/offers_controller.rb
app/controllers/point_of_interests_controller.rb
app/controllers/tours_controller.rb
app/services/converter/base.rb
app/views/constructions/_form.html.erb
app/views/events/_form.html.erb
app/views/jobs/_form.html.erb
app/views/news_items/_form.html.erb
app/views/offers/_form.html.erb
app/views/point_of_interests/_form.html.erb
app/views/tours/_form.html.erb

based on main-server PR: https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/210
- adjusted all resources
- in the past often outdated or wrong ids were used in calls to edit pages which failed with an error
- now we rescue graphql errors and redirect to the index pages instead with an flash error message
SVA-176

Update records instead of deleting and creating

---

app/controllers/waste_calendar_controller.rb

- with latest main server change the need for parsing
jsons was removed, as proper jsons are returned
SVA-422

fix: remove json parse for static content response

---

app/views/shared/partials/_media_contents_form.html.erb

- set the block for caption text to hidden, as there is no application
that renders the caption text
- did not remove it entirely, to ensure that possible data will not be removed
when saving media contents
- values will still be read and written with the form
SVA-494

feat: hide caption text of media contents

---

app/controllers/waste_calendar_controller.rb

`query { publicJsonFile(name: "wasteTypes") {content} ` Liefert ein String statt einem JSOn Datensatz ohne den Zusatz der Version
SVA-535

WasteCalendar: Add missing version to receive JSON instead of string

---

app/javascript/packs/application.js
app/javascript/partials/_fileupload.js
app/javascript/partials/_nested_forms.js
app/views/shared/partials/_media_contents_form.html.erb

- moved fileupload.js to partials folder as `packs` should contain just auto generated files and this js is used for the `_fileupload` erb partial
- auto linted files
- removed code because after deleting all existing file sections and starting over again with adding one, functionality was not bind due to that early return
- it was only working again after adding at least a second file section to have a length larger than 1 to bypass the condition
SVA-626

fix(fileupload): after removing file sections

---

app/views/events/_form.html.erb

Adds an OpenStruct if there is no address in graphql response to get the form rendered.
SVA-495

fix: Add empty address to edit form

---

app/controllers/tours_controller.rb
app/javascript/partials/_leaflet_map.js
app/views/tours/_form.html.erb
app/views/tours/form_partials/_tour_path.html.erb

This is the first prerequisite for creating and editing AR for tours. In order to place, create and edit AR entries we show the tour route with start and end point.
SVA-572

feat(tour): show tour routes in edit form

---

app/services/importer/waste_calendar.rb

In Zeile 43 konnte es vermutlich dazu kommen dass 'Lücken' gefüllt werden mit nicht existiernden Touren, wenn sowohl bei der Tour als auch bei der Adresse an einem Dateum nichts eingetragen war.
SVA-922

Überspringe den Fall "nil == nil"

---

app/assets/stylesheets/custom.css
app/javascript/packs/application.js
app/views/waste_calendar/new.html.erb

Die neueste Version der App enthält Funktionen, um nur noch Veränderungen an der Tour-Matrix zu speichern. Diese Änderungen ermöglichen es Benutzern, bestimmte Adressen für bestimmte Touren schneller zu speichern. Außerdem wird eine Bestätigung angezeigt, um dem Benutzer mitzuteilen, dass die Änderungen gespeichert wurden.
SVA-947

Änderungen an der Tour-Matrix speichern

---

app/controllers/events_controller.rb

Der Preis wird nun immer zu einem float umgewandelt, auch wenn er nicht angegeben ist.
Vorraussetzung dafür ist, das dann wenigstens die Beschreibung ausgefüllt ist:
Wenn also die Beschreibung des Preises oder der Wert Preis angegeben ist, dann wird der Wert des preises immer zu einem Float umgewandelt, was nun auch bei einem freilassen zu 0.0 führt.
Die führt nun nicht mehr zu einem Fehler, wenn eine kostenlose Preiskategorie angegeben werden soll, bei der nur die Beschreibung ausgefüllt wurde.
SVA-1090

Preiseingabe kann leer bleiben

---

app/controllers/events_controller.rb
app/views/events/_form.html.erb
app/views/events/index.html.erb
app/views/shared/partials/_dates_form.html.erb
app/views/shared/partials/_push_notifications_form.html.erb
app/views/shared/partials/_recurring_dates_form.html.erb

This PR introduces an interface to setup recurring dates for events.
| Not recurring | Recurring every day | Recurring on few days every two weeks | Recurring every four months | Recurring every year |
| --------------- | --------------- | --------------- | --------------- | --------------- |
| <img width="922" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-cms/assets/1942953/6a683dff-8653-434d-9930-1dca13a2f679"> | <img width="922" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-cms/assets/1942953/c960f0bd-e213-42ec-88be-022b0aaef3a1"> | <img width="929" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-cms/assets/1942953/0d19f125-b662-437f-be95-01f763079b76"> | <img width="921" alt="image" …

feat(event): recurring dates

---

app/helpers/application_helper.rb
app/javascript/packs/application.js
app/views/constructions/index.html.erb
app/views/deadlines/index.html.erb
app/views/defect_reports/index.html.erb
app/views/encounters_supports/show.html.erb
app/views/events/index.html.erb
app/views/jobs/index.html.erb
app/views/news_items/index.html.erb
app/views/noticeboards/index.html.erb
app/views/offers/index.html.erb
app/views/point_of_interests/index.html.erb
app/views/static_contents/index.html.erb
app/views/survey_comments/index.html.erb
app/views/surveys/index.html.erb
app/views/tours/index.html.erb
package.json
yarn.lock

This Pull Request introduces sorting with HTML data-sort (timestamp-integers) and remove moment.js
1. add sort for created_at and updated_at columns
2. add sort for date_start, date_end, and to_end columns
3. remove moment-related code and dependencies
SVA-1122

fix: sorting function for date fields

---

app/controllers/events_controller.rb
app/services/converter/base.rb

the issue was due to incorrect arguments order passed to the buildMutation function from the commit 257354e8f6b946b831d05178633a7108d3e45f01
SVA-1144

fix: error if create static content

---

app/controllers/point_of_interests_controller.rb
app/controllers/tours_controller.rb
app/views/point_of_interests/index.html.erb
app/views/tours/index.html.erb

Extended the category display feature, which was already present in the Events and News list views, to now also show in the POI (Point of Interest) and Tours list views.
SVA-1121

feat: added category display to POI and tours in list view

---

app/controllers/dashboard_controller.rb
app/controllers/noticeboards_controller.rb
app/views/dashboard/index.html.erb
app/views/noticeboards/index.html.erb

- added loading of different categorized noticeboards if present through category settings, falling back to the default one to ensure backwards compatibility
- added ability to load categorized noticeboard overviews to be linked to from the dashboard with specific name and items
|dashboard|index|
|---|---|
|<img width="1231" alt="image" src="https://github.com/user-attachments/assets/caa0f435-da43-4f81-8f56-d15ff320a362">|<img width="1412" alt="image" src="https://github.com/user-attachments/assets/f80c490a-c221-4817-9fc2-8d5c43c943a6">|
SVAK-51

feat(categories): render multiple noticeboards for different categories on dashboard
